version: 2

sources:
  - name: postgres
    database: postgres
    schema: public
    tables:
      - name: stock_data

models:
  - name: performance
    description: "Calculates the performance of each stock index"
    columns:
      - name: index_name
        description: "The name of the stock index"
        data_tests:
          - not_null
      - name: performance
        description: "The calculated performance of the stock index"
        data_tests:
          - not_null
