stock_data:  # This should match the profile name in your dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: Volubilis31*
      dbname: postgres
      schema: public
      threads: 1
      port: 5432
