stock_data: 
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal #localhost
      user: postgres
      password: Eviden2025BDX**
      dbname: postgres
      schema: public
      threads: 1
      port: 5432
