version: 2

sources:
  - name: postgres
    database: postgres
    schema: public
    tables:
      - name: stock_data_prices
      - name: inflation_rates
      - name: interest_rates
      - name: stock_data_volumes


models:
  - name: performance
    description: "Calcule la performance des indices boursiers entre la première et la dernière valeur."
    tests:
      - not_null:
          column_name: indice
      - not_null:
          column_name: performance
      - not_null:
          column_name: first_value
      - not_null:
          column_name: last_value
    columns:
      - name: indice
        description: "Nom de l'indice boursier."
      - name: performance
        description: "Performance de l'indice en pourcentage."
      - name: first_value
        description: "Première valeur enregistrée de l'indice."
      - name: last_value
        description: "Dernière valeur enregistrée de l'indice."

  - name: correlation
    description: "Calcule les corrélations entre différentes paires d'indices boursiers."
    tests:
      - not_null:
          column_name: indice_a
      - not_null:
          column_name: indice_b
      - not_null:
          column_name: correlation
    columns:
      - name: indice_a
        description: "Nom du premier indice dans la paire de corrélation."
      - name: indice_b
        description: "Nom du second indice dans la paire de corrélation."
      - name: correlation
        description: "Coefficient de corrélation entre les deux indices."


  - name: interest_rates_real
    description: "Calcule les taux d'intérets réels ajustés à l'inflation."
    columns:
      - name: USA
        description: "Taux ajustés USA."
      - name: Japon
        description: "Taux ajustés Japon."
      - name: France
        description: "Taux ajustés France."
      - name: Europe
        description: "Taux ajustés Europe."

  - name: average_volume
    description: "Calcule le volume moyen échangé par jour par indice."
    columns:
      - name: indice
        description: "Nom de l'indice boursier."
      - name: average_volume
        description: "Volume moyen de l'indice échangé."

  - name: cumulative_inflation
    description: "Calcule l'inflation cumulée au fil des années."
    columns:
      - name: région
      - name: taux_inflation_cumulé


  - name: cumulative_interest
    description: "Calcule les taux d'intérets cumulés au fil des années."
    columns:
      - name: région
      - name: taux_interest_cumulé